### ISSUE TITLE
Maybe make the whole box a hyperlink?

### ISSUE THREAD

**Issue by sixcorners** [splitgraph/splitgraph.com#188]
https://www.splitgraph.com/docs
On this page there are the Read, Try, and See boxes. Currently you have to click directly on the text to go there. It looks like a button though. It kind of feels like the whole rectangle should be able to be clicked.
https://github.com/splitgraph/splitgraph.com/blob/de2a8ec37316dfe0177992f68436e160484be844/docs/pages/docs/index.js#L21

**Comment by onpaws** [comment]
I believe this issue was addressed in a recent update.

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/182515/175036222-5224b610-4f62-43f9-bc7f-2c1d9a0e056e.png">

The 'whole button' should now be clickable.

**Comment by sixcorners** [comment]
Appears so. Thanks!
